name: CI
on: push
jobs:
  test:
    name: Lint, typecheck, build & test
    runs-on: ubuntu-latest

    # Start a Postgres instance, which is used during tests
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: kickstart
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      # This needs to match the POSTGRES_* env variables set in the Postgres service above
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/kickstart

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Install pnpm
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7

      # Install Node.js 16
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      # Install dependencies
      - name: Install dependencies
        run: pnpm install

      # Copy the example .env file
      - name: Copy example env
        run: cp .env.example .env

      # Run the generate
      - name: Generate
        run: pnpm run generate

      # Run the database migrations
      - name: Migrate the CI database
        run: pnpm run prisma:migrate

      # Lint the code
      - name: Lint
        run: pnpm run lint

      # Typecheck the code
      - name: Typecheck
        run: pnpm run typecheck

      # Build the code
      - name: Build
        run: pnpm run build

      # Run the unit tests
      - name: Run unit tests
        run: pnpm run test:unit

      # Install the Playwright browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Run the end-to-end tests
      - name: Run end-to-end tests
        run: pnpm run test:e2e

      # Upload the Playwright report
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
